version: "3"
services:
  python-container:
    container_name: estacio-python
    build:
      context: . # Diretório onde está localizado o Dockerfile
    volumes:
      - .:/app
    ports:
      - 5000:5000
    command: ["tail", "-f", "/dev/null"]
