version: '3'
services:
  python-container:
    container_name: estacio-python
    build:
      context: . # Diretório onde está localizado o Dockerfile
    volumes:
      - .:/app
    command: ["tail", "-f", "/dev/null"]